apiVersion: v1
kind: PersistentVolume
metadata:
  name: inv-redis-pv-3
spec:
  storageClassName: inv-redis-local-storage
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data-3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: inv-redis-pv-4
spec:
  storageClassName: inv-redis-local-storage
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data-4"