apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
        - name: inventoryservice
          image: kemtardif/articleservice:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: inventory-config
          volumeMounts:
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: inventory-appsettings-secret
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: inventoryservice
  ports: 
    - name: invsrvport
      protocol: TCP
      port: 80
      targetPort: 80


