apiVersion: v1
kind: PersistentVolume
metadata:
  name: po-redis-pv-1
spec:
  storageClassName: po-redis-local-storage
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: po-redis-pv-2
spec:
  storageClassName: po-redis-local-storage
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data-2"