apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: po-redis-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete