apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-psql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: so-psql
  template:
    metadata:
      labels:
        app: so-psql
    spec:      
      containers:
        - name: so-psql
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: so-psql-secret
          volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: so-psql-pv-storage
      volumes:
        - name: so-psql-pv-storage
          persistentVolumeClaim:
            claimName: so-psql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: so-psql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: so-psql
  ports:
  - name: so-psql-p
    protocol: TCP
    port: 5432
    targetPort: 5432

