apiVersion: v1
kind: Service
metadata:
  name: so-redis-srv
  labels:
    app: so-redis
spec:
  selector:
    app: so-redis
  clusterIP: None
  ports:
  - name: so-redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  


