apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: so-redis
spec:
  selector:
    matchLabels:
      app: so-redis
  serviceName: so-redis-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: so-redis
    spec:
      initContainers:
      - name: init-redis
        image: redis:latest
        command:
        - bash
        - "-c"
        - |
          set -ex
          cp /mnt/so-redis.conf /etc/so-redis.conf        
        volumeMounts:
        - name: redis-claim
          mountPath: /etc
        - name: config-map
          mountPath: /mnt/
      containers:
      - name: so-redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis-ss
        command:
          - redis-server
          - "/etc/so-redis.conf"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-claim
          mountPath: /etc
      volumes:
        - name: config-map
          configMap:
            name: so-redis-config 
  volumeClaimTemplates:
  - metadata:
      name: redis-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 150Mi
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 150Mi


