apiVersion: v1
kind: PersistentVolume
metadata:
  name: art-psql-pv
  labels:
    type: local
    app: art-psql
spec:
  storageClassName: manual    
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: art-psql-pvc
  labels:
    app: art-psql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

