apiVersion: apps/v1
kind: Deployment
metadata:
  name: art-psql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: art-psql
  template:
    metadata:
      labels:
        app: art-psql
    spec:      
      containers:
        - name: art-psql
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: art-psql-secret      
          volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: art-psql-pv-storage
      volumes:
        - name: art-psql-pv-storage
          persistentVolumeClaim:
            claimName: art-psql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: art-psql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: art-psql
  ports:
  - name: art-psql
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: art-psql-nodeport-srv
spec:
  type: NodePort
  selector:
    app: art-psql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

